### ISSUE TITLE
Xin info

### ISSUE THREAD

**Issue by chungtdnatv** [NguyenVanThanhHust/Twitch_SLAM#1]
Chào bạn.
Mình là Chung, mình đang tìm hiểu về SLAM và tìm được code của bạn.
Mình đang chạy thử tuy nhiên đang gặp chút vấn đề khi import pangolin nên muốn xin thông tin của bạn để mình hỏi 1 chút được không ạ?
Mình xin cảm ơn và hậu tạ ạ ^^

**Comment by NguyenVanThanhHust** [comment]
Bạn gặp vấn đề gì nhỉ?

**Comment by chungtdnatv** [comment]
> Bạn gặp vấn đề gì nhỉ?

Cảm ơn b đã rep. Hôm trước mình gặp lỗi khi cài thư viện pangolin nhưng fix được rồi ạ. Mình đang tìm hiểu về SLAM mà khó ghê hi
